In [1]:
import pandas as pd
import numpy as np
from orangecontrib.recommendation import *
import pyfpgrowth

df = pd.read_csv('201703_Taiwan.csv')
df = df[df['device_id']=='74DA388FF5F6']#74DA3895C3E0#74DA388FF5F6
df = df.reset_index(drop=True)

a = pd.qcut(df['PM1'],5,labels=False,retbins=True)
b = pd.qcut(df['PM10'],5,labels=False,retbins=True)
c = pd.qcut(df['Humidity'],5,labels=False,retbins=True)
#print(a[0])
print(a[1])
print(b[1])
print(c[1])

for i in range(0,a[0].size):
    index1 = a[0][i]
    index2 = b[0][i]
    index3 = c[0][i]
    df['PM1'][i] = (a[1][index1]+a[1][index1+1])/2
    df['PM10'][i] = (b[1][index2]+b[1][index2+1])/2
    df['Humidity'][i] = (c[1][index3]+c[1][index3+1])/2
df



[   2.   24.   32.   40.   46.  156.]
[   2.   32.   53.   69.   81.  173.]
[  54.   67.   74.   80.   88.  100.]

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:23: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:24: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


Date      Time     device_id  PM2.5  PM10  PM1  Temperature  \
0     2017-03-01  08:00:00  74DA388FF5F6     41    42   28        20.00   
1     2017-03-01  08:29:35  74DA388FF5F6     48    61   36        20.12   
2     2017-03-01  08:41:25  74DA388FF5F6     47    61   36        19.87   
3     2017-03-01  08:53:16  74DA388FF5F6     57    75   43        19.37   
4     2017-03-01  09:11:00  74DA388FF5F6     70   127  101        19.62   
5     2017-03-01  09:16:55  74DA388FF5F6     55    61   43        19.37   
6     2017-03-01  09:22:49  74DA388FF5F6     44    42   28        19.25   
7     2017-03-01  09:28:43  74DA388FF5F6     43    42   28        19.12   
8     2017-03-01  09:34:41  74DA388FF5F6     42    42   28        19.12   
9     2017-03-01  09:46:32  74DA388FF5F6     41    42   28        19.25   
10    2017-03-01  09:52:26  74DA388FF5F6     42    42   28        19.50   
11    2017-03-01  10:04:19  74DA388FF5F6     42    42   28        20.00   
12    2017-03-01  10:57:35  74DA388FF5F6     56    61   43        20.50   
13    2017-03-01  11:03:30  74DA388FF5F6     52    61   36        20.50   
14    2017-03-01  11:45:00  74DA388FF5F6     51    61   36        21.12   
15    2017-03-01  11:50:54  74DA388FF5F6     46    61   36        21.00   
16    2017-03-01  11:56:49  74DA388FF5F6     40    42   28        21.00   
17    2017-03-01  12:14:38  74DA388FF5F6     43    42   28        20.50   
18    2017-03-01  12:38:16  74DA388FF5F6     41    42   28        20.62   
19    2017-03-01  13:37:21  74DA388FF5F6     37    42   28        21.00   
20    2017-03-01  13:43:15  74DA388FF5F6     38    42   28        21.00   
21    2017-03-01  14:18:44  74DA388FF5F6     32    42   28        21.25   
22    2017-03-01  14:42:38  74DA388FF5F6     32    42   28        21.50   
23    2017-03-01  14:48:33  74DA388FF5F6     35    42   28        21.50   
24    2017-03-01  15:06:15  74DA388FF5F6     38    42   28        21.50   
25    2017-03-01  15:18:07  74DA388FF5F6     35    42   28        21.00   
26    2017-03-01  15:24:01  74DA388FF5F6     37    42   28        21.12   
27    2017-03-01  15:29:55  74DA388FF5F6     34    42   28        20.75   
28    2017-03-01  15:41:44  74DA388FF5F6     43    42   28        20.75   
29    2017-03-01  16:11:16  74DA388FF5F6     36    42   28        20.62   
...          ...       ...           ...    ...   ...  ...          ...   
1472  2017-03-30  07:52:54  74DA388FF5F6     55    61   36        24.87   
1473  2017-03-30  07:58:48  74DA388FF5F6     55    75   36        25.00   
1474  2017-03-30  08:04:43  74DA388FF5F6     53    61   36        25.00   
1475  2017-03-30  08:10:37  74DA388FF5F6     52    61   36        25.00   
1476  2017-03-30  08:22:27  74DA388FF5F6     56    75   36        25.00   
1477  2017-03-30  08:28:22  74DA388FF5F6     57    75   43        25.12   
1478  2017-03-30  08:34:17  74DA388FF5F6     56    75   36        25.25   
1479  2017-03-30  08:40:12  74DA388FF5F6     56    75   36        25.12   
1480  2017-03-30  08:52:01  74DA388FF5F6     56    75   43        25.50   
1481  2017-03-30  08:57:56  74DA388FF5F6     57    75   43        25.62   
1482  2017-03-30  09:21:36  74DA388FF5F6     64    75  101        25.75   
1483  2017-03-30  09:27:30  74DA388FF5F6     63    75  101        25.87   
1484  2017-03-30  09:39:20  74DA388FF5F6     71   127  101        26.00   
1485  2017-03-30  09:45:16  74DA388FF5F6     74   127  101        26.12   
1486  2017-03-30  09:51:11  74DA388FF5F6     73   127  101        26.25   
1487  2017-03-30  09:57:06  74DA388FF5F6     68   127  101        26.37   
1488  2017-03-30  10:20:47  74DA388FF5F6     83   127  101        26.75   
1489  2017-03-30  10:32:37  74DA388FF5F6     74   127  101        27.12   
1490  2017-03-30  10:38:33  74DA388FF5F6     68   127  101        27.25   
1491  2017-03-30  10:56:18  74DA388FF5F6     71   127  101        27.75   
1492  2017-03-30  11:02:13  74DA388FF5F6     68   127  101        27.75   
1493  2017-03-30  11:19:59  74DA388FF

In [2]:
for j in df.index:
    print('pm1:',df['PM1'][j],' pm10:',df['PM10'][j],' humidity:',df['Humidity'][j],sep='')

df1 = df
df1['PM1'] = df['PM1']+1000
df1['PM10'] = df['PM10'] +2000
df1['Humidity'] = df['Humidity'] +3000
df1 = df1[['PM1','PM10','Humidity']]

fp_support = 0.10
fp_confidance = 0.90
print('\nmin_Support: ', fp_support, ' min_Condifance: ', fp_confidance)
print('+1000:PM1')
print('+2000:PM10')
print('+3000:Humidity')
#print(df.values.tolist())
from orangecontrib.associate.fpgrowth import * 
itemset = dict(frequent_itemsets(df1.values.tolist(), fp_support)) #support greater than two transactions:
rules = association_rules(itemset, fp_confidance)
print('\nfp-growth algorithm\nX, Y, Support counts, Confidence\n')
for i in list(rules):
    print (i)


pm1:28 pm10:42 humidity:94
pm1:36 pm10:61 humidity:84
pm1:36 pm10:61 humidity:84
pm1:43 pm10:75 humidity:94
pm1:101 pm10:127 humidity:84
pm1:43 pm10:61 humidity:84
pm1:28 pm10:42 humidity:84
pm1:28 pm10:42 humidity:84
pm1:28 pm10:42 humidity:84
pm1:28 pm10:42 humidity:84
pm1:28 pm10:42 humidity:84
pm1:28 pm10:42 humidity:84
pm1:43 pm10:61 humidity:84
pm1:36 pm10:61 humidity:84
pm1:36 pm10:61 humidity:84
pm1:36 pm10:61 humidity:84
pm1:28 pm10:42 humidity:84
pm1:28 pm10:42 humidity:77
pm1:28 pm10:42 humidity:77
pm1:28 pm10:42 humidity:77
pm1:28 pm10:42 humidity:77
pm1:28 pm10:42 humidity:70
pm1:28 pm10:42 humidity:70
pm1:28 pm10:42 humidity:70
pm1:28 pm10:42 humidity:60
pm1:28 pm10:42 humidity:60
pm1:28 pm10:42 humidity:60
pm1:28 pm10:42 humidity:60
pm1:28 pm10:42 humidity:60
pm1:28 pm10:42 humidity:60
pm1:28 pm10:42 humidity:60
pm1:28 pm10:42 humidity:60
pm1:28 pm10:42 humidity:60
pm1:36 pm10:42 humidity:60
pm1:36 pm10:42 humidity:60
pm1:36 pm10:61 humidity:60
pm1:101 pm10:75 humidity:6

pm1:101 pm10:127 humidity:84
pm1:101 pm10:127 humidity:84
pm1:101 pm10:127 humidity:84
pm1:101 pm10:127 humidity:84
pm1:101 pm10:127 humidity:84
pm1:101 pm10:127 humidity:84
pm1:36 pm10:61 humidity:77
pm1:28 pm10:42 humidity:84
pm1:36 pm10:61 humidity:77
pm1:36 pm10:61 humidity:77
pm1:43 pm10:61 humidity:77
pm1:43 pm10:75 humidity:77
pm1:43 pm10:75 humidity:77
pm1:43 pm10:61 humidity:77
pm1:43 pm10:61 humidity:77
pm1:43 pm10:61 humidity:77
pm1:101 pm10:75 humidity:70
pm1:101 pm10:75 humidity:77
pm1:43 pm10:75 humidity:77
pm1:101 pm10:75 humidity:77
pm1:101 pm10:127 humidity:70
pm1:101 pm10:127 humidity:70
pm1:101 pm10:127 humidity:70
pm1:101 pm10:127 humidity:70
pm1:101 pm10:127 humidity:70
pm1:101 pm10:127 humidity:77
pm1:101 pm10:127 humidity:70
pm1:101 pm10:127 humidity:70
pm1:101 pm10:127 humidity:70
pm1:101 pm10:127 humidity:70
pm1:101 pm10:127 humidity:70
pm1:101 pm10:127 humidity:70
pm1:43 pm10:75 humidity:70
pm1:43 pm10:75 humidity:70
pm1:36 pm10:61 humidity:70
pm1:36 pm10:61 h

pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:94
pm1:13 pm10:17 humidity:84
pm1:13 pm10:17 humidity:84
pm1:13 pm10:17 humidity:84
pm1:13 pm10:17 humidity:84
pm1:13 pm10:17 humidity:84
pm1:13 pm10:17 humidity:84
pm1:13 pm10:17 humidity:84
pm1:13 pm10:17 humidity:84
pm1:13 pm10:17 humidity:84
p

pm1:36 pm10:75 humidity:77
pm1:36 pm10:75 humidity:77
pm1:36 pm10:75 humidity:77
pm1:36 pm10:75 humidity:77
pm1:36 pm10:75 humidity:77
pm1:43 pm10:75 humidity:77
pm1:43 pm10:75 humidity:77
pm1:36 pm10:75 humidity:77
pm1:36 pm10:75 humidity:84
pm1:36 pm10:75 humidity:77
pm1:43 pm10:75 humidity:84
pm1:36 pm10:75 humidity:84
pm1:43 pm10:75 humidity:77
pm1:43 pm10:75 humidity:84
pm1:43 pm10:75 humidity:84
pm1:43 pm10:75 humidity:84
pm1:43 pm10:75 humidity:84
pm1:43 pm10:75 humidity:84
pm1:43 pm10:75 humidity:84
pm1:43 pm10:75 humidity:84
pm1:43 pm10:75 humidity:84
pm1:43 pm10:75 humidity:84
pm1:43 pm10:75 humidity:84
pm1:43 pm10:75 humidity:84
pm1:43 pm10:75 humidity:84
pm1:43 pm10:75 humidity:77
pm1:43 pm10:75 humidity:84
pm1:43 pm10:75 humidity:77
pm1:36 pm10:75 humidity:77
pm1:43 pm10:75 humidity:77
pm1:43 pm10:75 humidity:77
pm1:43 pm10:75 humidity:77
pm1:43 pm10:75 humidity:77
pm1:43 pm10:75 humidity:77
pm1:43 pm10:75 humidity:77
pm1:43 pm10:75 humidity:77
pm1:43 pm10:75 humidity:77
p

pm1:43 pm10:75 humidity:77
pm1:101 pm10:127 humidity:77
pm1:101 pm10:127 humidity:77
pm1:101 pm10:127 humidity:77
pm1:101 pm10:127 humidity:77
pm1:101 pm10:127 humidity:77
pm1:101 pm10:127 humidity:77
pm1:101 pm10:127 humidity:77
pm1:101 pm10:127 humidity:77
pm1:101 pm10:127 humidity:77
pm1:43 pm10:75 humidity:77
pm1:43 pm10:75 humidity:77
pm1:43 pm10:75 humidity:70
pm1:43 pm10:75 humidity:70
pm1:43 pm10:75 humidity:70
pm1:43 pm10:75 humidity:70
pm1:36 pm10:75 humidity:70
pm1:43 pm10:75 humidity:70
pm1:43 pm10:75 humidity:70
pm1:43 pm10:75 humidity:70
pm1:43 pm10:75 humidity:70
pm1:43 pm10:75 humidity:70
pm1:43 pm10:75 humidity:70
pm1:43 pm10:75 humidity:70
pm1:43 pm10:75 humidity:70
pm1:43 pm10:75 humidity:70
pm1:43 pm10:75 humidity:70
pm1:101 pm10:75 humidity:70
pm1:101 pm10:75 humidity:70
pm1:101 pm10:127 humidity:70
pm1:101 pm10:127 humidity:70
pm1:101 pm10:127 humidity:70
pm1:101 pm10:127 humidity:60
pm1:101 pm10:127 humidity:60
pm1:101 pm10:127 humidity:70
pm1:101 pm10:127 humidi