In [22]:
from sklearn.cluster import KMeans
import numpy as np
import pandas as pd
df = pd.read_csv('201703_Taiwan.csv')
df = df[df['device_id']=='74DA388FF5F6']
df = df.reset_index(drop=True)
df = df[['PM1','PM10','Humidity']]
X = df.as_matrix()

kmeans = KMeans(n_clusters=15, random_state=0).fit(X)
kmeans.labels_

for i in range(0,len(df)):
    tmp = kmeans.labels_[i] #0~9
    df['PM1'][i] = kmeans.cluster_centers_[tmp][0]
    df['PM10'][i] = kmeans.cluster_centers_[tmp][1]
    df['Humidity'][i] = kmeans.cluster_centers_[tmp][2]


print(kmeans.cluster_centers_)
print(df)
for j in df.index:
    print('pm1:',df['PM1'][j],' pm10:',df['PM10'][j],' humidity:',df['Humidity'][j],sep='')

[[  46.86029412   82.53676471   83.04411765]
 [  16.57017544   21.14035088   90.40350877]
 [ 110.02777778  122.86111111   79.66666667]
 [  30.425        48.34166667   58.45      ]
 [  34.5971223    58.77697842   67.37410072]
 [  66.87912088   88.71428571   72.30769231]
 [  39.53061224   68.7244898    77.85204082]
 [ 134.6         149.16666667   78.53333333]
 [  33.62962963   56.07407407   91.33333333]
 [  27.43902439   39.26829268   70.20731707]
 [  44.61170213   77.16489362   70.87765957]
 [  25.98850575   36.29885057   92.06896552]
 [   7.464         9.464        91.056     ]
 [  18.88888889   25.28888889   67.91111111]
 [  89.625       104.875        77.        ]]
      PM1  PM10  Humidity
0      33    56        91
1      33    56        91
2      33    56        91
3      39    68        77
4      46    82        83
5      39    68        77
6      33    56        91
7      33    56        91
8      33    56        91
9      33    56        91
10     33    56        91
11     33   

pm1:110 pm10:122 humidity:79
pm1:110 pm10:122 humidity:79
pm1:110 pm10:122 humidity:79
pm1:110 pm10:122 humidity:79
pm1:134 pm10:149 humidity:78
pm1:134 pm10:149 humidity:78
pm1:110 pm10:122 humidity:79
pm1:110 pm10:122 humidity:79
pm1:110 pm10:122 humidity:79
pm1:110 pm10:122 humidity:79
pm1:110 pm10:122 humidity:79
pm1:110 pm10:122 humidity:79
pm1:110 pm10:122 humidity:79
pm1:110 pm10:122 humidity:79
pm1:110 pm10:122 humidity:79
pm1:110 pm10:122 humidity:79
pm1:110 pm10:122 humidity:79
pm1:110 pm10:122 humidity:79
pm1:39 pm10:68 humidity:77
pm1:27 pm10:39 humidity:70
pm1:34 pm10:58 humidity:67
pm1:39 pm10:68 humidity:77
pm1:39 pm10:68 humidity:77
pm1:44 pm10:77 humidity:70
pm1:39 pm10:68 humidity:77
pm1:39 pm10:68 humidity:77
pm1:39 pm10:68 humidity:77
pm1:39 pm10:68 humidity:77
pm1:44 pm10:77 humidity:70
pm1:44 pm10:77 humidity:70
pm1:44 pm10:77 humidity:70
pm1:44 pm10:77 humidity:70
pm1:44 pm10:77 humidity:70
pm1:46 pm10:82 humidity:83
pm1:66 pm10:88 humidity:72
pm1:66 pm10:88 humi

pm1:33 pm10:56 humidity:91
pm1:33 pm10:56 humidity:91
pm1:33 pm10:56 humidity:91
pm1:33 pm10:56 humidity:91
pm1:33 pm10:56 humidity:91
pm1:33 pm10:56 humidity:91
pm1:33 pm10:56 humidity:91
pm1:33 pm10:56 humidity:91
pm1:33 pm10:56 humidity:91
pm1:33 pm10:56 humidity:91
pm1:33 pm10:56 humidity:91
pm1:33 pm10:56 humidity:91
pm1:33 pm10:56 humidity:91
pm1:33 pm10:56 humidity:91
pm1:33 pm10:56 humidity:91
pm1:33 pm10:56 humidity:91
pm1:33 pm10:56 humidity:91
pm1:33 pm10:56 humidity:91
pm1:33 pm10:56 humidity:91
pm1:25 pm10:36 humidity:92
pm1:25 pm10:36 humidity:92
pm1:25 pm10:36 humidity:92
pm1:33 pm10:56 humidity:91
pm1:25 pm10:36 humidity:92
pm1:25 pm10:36 humidity:92
pm1:33 pm10:56 humidity:91
pm1:33 pm10:56 humidity:91
pm1:25 pm10:36 humidity:92
pm1:25 pm10:36 humidity:92
pm1:25 pm10:36 humidity:92
pm1:25 pm10:36 humidity:92
pm1:25 pm10:36 humidity:92
pm1:25 pm10:36 humidity:92
pm1:25 pm10:36 humidity:92
pm1:25 pm10:36 humidity:92
pm1:25 pm10:36 humidity:92
pm1:25 pm10:36 humidity:92
p

pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:39 pm10:68 humidity:77
pm1:44 pm10:77 humidity:70
pm1:44 pm10:77 humidity:70
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:34 pm10:58 humidity:67
pm1:30 pm10:48 humidity:58
pm1:30 pm10:48 humidity:58
pm1:34 pm10:58 humidity:67
p